travis:
  secure:
    BINSTAR_TOKEN: MxAeemymLXDgo26D5CMSVVfFc3aT0AuOswwnaujjV4MuyoPBvaD7O+O5ZUwFk+cWWajoIlEPbIZA0nJ/eODWmUvlSKGNgtwqbS5yronGR9XGSCn5hk0TY2AT5eWPRXKKTeZZjE4O+GdSvhj2JgbDwXFkBY2ZkOiVb1icEuxFF5YlUH9xGzYemap8sAUtGdkBzvM/rzW0vZme5rds/A6IasZGGLmmljSwHiPq/75sMLkY+hmVtpDduuOp0KTjs0B7/PfngK+q+GSPs0WjfGOkKN840ZuXlwEP39cIMDMgA+WqOgWtn9wFWXz9sUQCDvLcRVVXHmF/NnnQjM8pF+0G7kHvRsS42OqcX6iM5RZgfXOqfcAyu4CSWJ3yxiaOnMTDLh8OAiJrPoKX7iTmZWb2osdI69DQzCm5xC2lFIzHsovlnjlENfiNpKTKbMynHvRWbzyI6eRAZCGJ7EbBT3KFa52k62+zCVvsP7woCZLgbwm3jns1STIhfRo1uhd3mJtPIYXYNnbNoRMbjt02n3b11gqzt5vIlgHk4k809qu2BjdDpQjbq237ZLPCenOYYj5ZETGRL+X9g+RNlM4sAnKED+0kH9NwHako4mVyIuP3qp82eLvHSGreOb24NyrCKGFAf+8zvfIvYtGwLFCeYWFeN6oG8+fWPRNYbmRrge0pCxM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
